sylius_backend_planning_index:
    path:     /
    methods: [GET]
    defaults: { _controller: AcmePeriodBundle:Planning:index }
sylius_backend_creneau_create:
    pattern: /new
    methods: [GET, POST]
    defaults: { _controller: AcmePeriodBundle:Planning:create }