parameters:
     sylius.model.period.class: Acme\Bundle\PeriodBundle\Entity\Period
     sylius.model.creneau.class: Acme\Bundle\PeriodBundle\Entity\Creneau

services:
     sylius.form.type.period:
         class: Acme\Bundle\PeriodBundle\Form\Type\PeriodType
         arguments: [%sylius.model.period.class%]
         tags: 
            - { name: form.type, alias: sylius_period }
            
     sylius.form.type.creneau:
         class: Acme\Bundle\PeriodBundle\Form\Type\CreneauType
         arguments: [%sylius.model.creneau.class%]
         tags: 
            - { name: form.type, alias: sylius_creneau }
            
     sylius.form.type.periodchoice:
         class: Acme\Bundle\PeriodBundle\Form\Type\PeriodEntityType
         arguments: [%sylius.model.period.class%]
         tags: 
            - { name: form.type, alias: acme_period_choice }

     acme.period.repository:
         class: Acme\Bundle\PeriodBundle\Entity\PeriodRepository
            
     acme.twig.period_helper:
         class: Acme\Bundle\PeriodBundle\Twig\AcmePeriodExtension
         arguments: 
            - @service_container
         tags:
            - { name: twig.extension }
     acme.listener.order_creneau:
         class: Acme\Bundle\PeriodBundle\EventListener\OrderShippingCreneauListener
         tags:
            - { name: kernel.event_listener, event: acme.checkout.finalize.creneau, method: calculAvailability }