parameters:
    # acme.entity.user.class: Acme\Bundle\ShopBundle\Entity\User
    sylius.checkout_step.addressing.class: Acme\Bundle\ShopBundle\Checkout\Step\AddressingStep
    sylius.checkout_step.shipping.class: Acme\Bundle\ShopBundle\Checkout\Step\ShippingStep
services:
    
