parameters:
    # acme.entity.user.class: Acme\Bundle\ShopBundle\Entity\User
    sylius.checkout_step.addressing.class: Acme\Bundle\ShopBundle\Checkout\Step\AddressingStep
    sylius.checkout_form.shipping.class: Acme\Bundle\ShopBundle\Form\Type\Checkout\ShippingStepType
    sylius.checkout_step.shipping.class: Acme\Bundle\ShopBundle\Checkout\Step\ShippingStep
    sylius.checkout_form.shipment.class: Acme\Bundle\ShopBundle\Form\Type\Checkout\ShipmentType
    sylius.checkout_step.finalize.class: Acme\Bundle\ShopBundle\Checkout\Step\FinalizeStep
    
services:
    acme.product.checker.helper:
        class: Acme\Bundle\ShopBundle\Templating\Helper\ProductCheckerHelper
        arguments: [@sylius.cart_provider,@form.factory]
        tags:
           -   { name: templating.helper, alias: product_checker_helper }

    acme.product.checker:
        class: Acme\Bundle\ShopBundle\Twig\ProductCheckerExtension
        arguments: [@acme.product.checker.helper]
        tags:
            -  { name: twig.extension }

    acme.form.type.shipping_creneau_choice:
        class: Acme\Bundle\ShopBundle\Form\Type\ShippingCreneauChoiceType
        arguments: [@sylius.shipping_methods_resolver,@service_container]
        tags:
            - { name: form.type, alias: sylius_shipping_creneau_choice }
