parameters:
     sylius.model.magasin.class: Acme\Bundle\MagasinBundle\Entity\Magasin

services:
     sylius.form.type.magasin:
         class: Acme\Bundle\MagasinBundle\Form\Type\MagasinType
         arguments: [%sylius.model.magasin.class%]
         tags: 
            - { name: form.type, alias: sylius_magasin }