parameters:
#    acme_web.example.class: Acme\Bundle\WebBundle\Example
    #sylius.form.frontend.registration.type.class: Acme\Bundle\ShopBundle\Form\RegistrationFormType
    #sylius.form.frontend.profile.type.class: Acme\Bundle\ShopBundle\Form\ProfileFormType
    fos_user.model.user.class: Acme\Bundle\ShopBundle\Entity\User
    #sylius.form.type.address.class: Acme\Bundle\ShopBundle\Form\Type\AddressType
    sylius.form.type.shipping_method_choice.class: Acme\Bundle\ShopBundle\Form\Type\ShippingMethodChoiceType
    sylius.menu_builder.frontend.class: Acme\Bundle\WebBundle\Menu\FrontendMenuBuilder
    sylius.controller.frontend.homepage.class: Acme\Bundle\WebBundle\Controller\Frontend\HomepageController
    sylius.controller.cart_item.class: Acme\Bundle\CartBundle\Controller\CartItemController
services:
    acme_reports.menu_builder:
        class: Acme\Bundle\WebBundle\EventListener\MenuBuilderListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu_builder.backend.main, method: addBackendMenuItems }
            - { name: kernel.event_listener, event: sylius.menu_builder.backend.sidebar, method: addBackendMenuItems }

    acme.menu.frontend.cart:
        class: Knp\Menu\MenuItem 
        factory_service: sylius.menu_builder.frontend
        factory_method: createCartMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: sylius.frontend.cart }
            
    acme.menu.frontend.cartitems:
        class: Knp\Menu\MenuItem 
        factory_service: sylius.menu_builder.frontend
        factory_method: createCartSidebarMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: sylius.frontend.cart.sidebar }

    acme.menu.frontend.promotions:
        class: Knp\Menu\MenuItem 
        factory_service: sylius.menu_builder.frontend
        factory_method: createPromotionsMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: sylius.frontend.promotions }
            
    acme.menu.frontend.taxonomies:
        class: Knp\Menu\MenuItem 
        factory_service: sylius.menu_builder.frontend
        factory_method: createTaxonomiesSidebarMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: sylius.frontend.taxonomies.sidebar }

    acme.menu.frontend.actualites:
        class: Knp\Menu\MenuItem 
        factory_service: sylius.menu_builder.frontend
        factory_method: createTopicMenu
        arguments: ["@request"]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: sylius.frontend.topic }
    
    sylius.menu_builder.frontend:
        class: Acme\Bundle\WebBundle\Menu\FrontendMenuBuilder
        arguments:  [@knp_menu.factory,@security.context,@translator,@event_dispatcher,@sylius.currency_provider,@sylius.repository.taxonomy,@sylius.repository.promotion,@sylius.cart_provider,@sylius.templating.helper.currency]
        calls:
            - [ setRequest, [ @request= ] ] 