parameters:
    acme_inscription.scenario.class: Acme\Bundle\InscriptionBundle\Process\InscriptionScenario
    acme_inscription.form.type.class: Acme\Bundle\InscriptionBundle\Form\Type\InscriptionType
    
services:
    acme_inscription.scenario:
        class: %acme_inscription.scenario.class%
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: sylius.process.scenario, alias: acme_inscription }
    acme_inscription.form.type.inscription:
        class: : %acme_inscription.form.type.class%
        argument: 'Acme\ShopBundle\Entity\User'
        tags:
            - { name: form.type, alias: inscription_user }