<?php

namespace Acme\Bundle\PeriodBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CreneauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreneauRepository extends EntityRepository
{
}
